"""test model synchronization

Revision ID: 2cd9d8ca3e87
Revises: 6948cc396105
Create Date: 2026-09-04 10:54:14.984011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd9d8ca3e87'
down_revision: Union[str, Sequence[str], None] = '6948cc396105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('employees', sa.Column('designation_id', sa.Integer(), nullable=True))
    op.execute("""
    UPDATE employees e
    SET designation_id = d.id
    FROM designations d
    WHERE e.designation = d.designation_name
""")
    op.create_foreign_key(None, 'employees', 'designations', ['designation_id'], ['id'])
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'designation_id')
    op.drop_column('employees', 'old_designation')
    # ### end Alembic commands ###
