"""add asset employee relationship

Revision ID: 6948cc396105
Revises: 906d88219528
Create Date: 2026-08-30 09:47:25.871732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6948cc396105'
down_revision: Union[str, Sequence[str], None] = '906d88219528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key( "fk_assets_employee_id", 'assets', 'employees', ['employee_id'], ['employee_id'])
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'assets', type_='foreignkey')
    # ### end Alembic commands ###
