"""Make employee profile fields optional

Revision ID: 928613c3a8b4
Revises: 734f95a47022
Create Date: 2026-09-26 18:22:58.897858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928613c3a8b4'
down_revision: Union[str, Sequence[str], None] = '734f95a47022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('employees', 'department_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('employees', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employees', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'department_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
