"""updating of employee id

Revision ID: b45eac99be93
Revises: 2cd9d8ca3e87
Create Date: 2026-09-05 10:56:21.009260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45eac99be93'
down_revision: Union[str, Sequence[str], None] = '2cd9d8ca3e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('designation', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
